[theme]
base="dark"
primaryColor = '#4691ce'
backgroundColor = '#ffffff'
secondaryBackgroundColor = '#4985c1'
textColor = '#000000'
font = 'sans serif'

[server]
enableXsrfProtection = false
enableCORS = false
port=8501

